# The URL the site will be built for
base_url = "https://edgl.dev"

title = "Edgar Luque"
description = "Software Developer"

default_language = "en"

generate_feeds = true

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# todo, when debian updates zola, enable this again, there is a bug where minify removes newlines in pre.
minify_html = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

taxonomies = [
    { name = "categories", feed = true},
]

[markdown.highlighting]
theme = "ayu-dark"
error_on_missing_language = true

[extra]
# Put all your custom variables here
